name: BlocksAnimation
version: '${project.version}'
main: me.blueslime.blocksanimations.BlocksAnimations
api-version: 1.13
authors: [ JustJustin ]
description: Make animations with minecraft blocks in specified regions
commands:
  banimation:
    description: Plugin Main Command